"""discovered_posts for the automation agent

Adds one table. **Purely additive** — no existing table, column or constraint is
touched, so applying it to a database with live campaigns changes nothing about
them and the downgrade is a clean drop.

The unique index on ``dedupe_key`` is the load-bearing part: it is what makes
duplicate processing impossible even if two discovery runs overlap. Enforcing it
in application code instead would leave a race between the check and the insert.

Revision ID: e3b93547d7ba
Revises: 355406ec1802
Created: 2026-08-13 09:59:20.512661+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e3b93547d7ba'
down_revision: str | None = '355406ec1802'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovered_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_posts_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_posts_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_discovered_posts_discovered_at'), ['discovered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_posts_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovered_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_posts_state'))
        batch_op.drop_index(batch_op.f('ix_discovered_posts_discovered_at'))
        batch_op.drop_index(batch_op.f('ix_discovered_posts_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_discovered_posts_campaign_id'))

    op.drop_table('discovered_posts')
    # ### end Alembic commands ###
