"""subscribers master mailing list

Revision ID: 295e6f2d2a77
Revises: 443113e32b9b
Created: 2026-08-13 10:48:07.533199+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '295e6f2d2a77'
down_revision: str | None = '443113e32b9b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('added_by', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscribers_added_at'), ['added_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscribers_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_is_active'))
        batch_op.drop_index(batch_op.f('ix_subscribers_added_at'))

    op.drop_table('subscribers')
    # ### end Alembic commands ###
