"""approval tokens

Revision ID: 443113e32b9b
Revises: e3b93547d7ba
Created: 2026-08-13 10:30:25.658135+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '443113e32b9b'
down_revision: str | None = 'e3b93547d7ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_tokens_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_tokens_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_approval_tokens_campaign_id'))

    op.drop_table('approval_tokens')
    # ### end Alembic commands ###
