"""initial schema

Revision ID: 355406ec1802
Revises: 
Created: 2026-08-05 19:09:23.760557+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '355406ec1802'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('logger', sa.String(length=128), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_logs', schema=None) as batch_op:
        batch_op.create_index('ix_logs_corr', ['correlation_id'], unique=False)
        batch_op.create_index('ix_logs_level', ['level'], unique=False)
        batch_op.create_index('ix_logs_ts', ['ts'], unique=False)

    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('was_truncated', sa.Boolean(), nullable=False),
    sa.Column('extractor_used', sa.String(length=32), nullable=False),
    sa.Column('extraction_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_articles_url_hash'), ['url_hash'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ai_title', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_newsletter', sa.Text(), nullable=True),
    sa.Column('ai_subject', sa.Text(), nullable=True),
    sa.Column('ai_preview_text', sa.Text(), nullable=True),
    sa.Column('ai_cta', sa.Text(), nullable=True),
    sa.Column('ai_keywords', sa.JSON(), nullable=True),
    sa.Column('ai_category', sa.String(length=64), nullable=True),
    sa.Column('ai_tone', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('newsletter', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('preview_text', sa.Text(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('cta_url', sa.String(length=2048), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('tone', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('generation_ms', sa.Integer(), nullable=False),
    sa.Column('regeneration_count', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('rendered_html', sa.Text(), nullable=True),
    sa.Column('rendered_text', sa.Text(), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('suppressions',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('reason', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('campaign_articles',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('section_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'article_id')
    )
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('invalid_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'email', name='uq_recipient_per_campaign')
    )
    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.create_index('ix_recipients_campaign', ['campaign_id'], unique=False)

    op.create_table('send_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('send_records', schema=None) as batch_op:
        batch_op.create_index('ix_send_campaign_status', ['campaign_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('send_records', schema=None) as batch_op:
        batch_op.drop_index('ix_send_campaign_status')

    op.drop_table('send_records')
    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.drop_index('ix_recipients_campaign')

    op.drop_table('recipients')
    op.drop_table('campaign_articles')
    op.drop_table('users')
    op.drop_table('suppressions')
    op.drop_table('settings')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_created_at'))

    op.drop_table('campaigns')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_url_hash'))
        batch_op.drop_index(batch_op.f('ix_articles_created_at'))

    op.drop_table('articles')
    with op.batch_alter_table('app_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_logs_ts')
        batch_op.drop_index('ix_logs_level')
        batch_op.drop_index('ix_logs_corr')

    op.drop_table('app_logs')
    # ### end Alembic commands ###
