"""email_events for like and unsubscribe

Revision ID: 44556bfc6465
Revises: d9573e65c18c
Created: 2026-08-19 18:16:19.475326+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '44556bfc6465'
down_revision: str | None = 'd9573e65c18c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'campaign_id', 'action', name='uq_email_event')
    )
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.create_index('ix_email_events_campaign_action', ['campaign_id', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_events_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_events_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_events_email'))
        batch_op.drop_index(batch_op.f('ix_email_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_email_events_campaign_id'))
        batch_op.drop_index('ix_email_events_campaign_action')

    op.drop_table('email_events')
    # ### end Alembic commands ###
